=== maiyasser21/XML/Day2/Lab2/schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="library">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="info">
          <xs:complexType>
            <xs:all>
              <xs:element name="location" type="xs:string" />
              <xs:element name="description" type="xs:string" />
              <xs:element name="librarian" type="xs:string" />
            </xs:all>
          </xs:complexType>
        </xs:element>
        <xs:element name="book">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string" />
              <xs:element name="author">
                <xs:complexType>
                  <xs:attribute name="Name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="preface" type="xs:string" />
              <xs:element name="part">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="title" type="xs:string" />
                    <xs:element maxOccurs="unbounded" name="chapter">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="title" type="xs:string" />
                          <xs:element name="section">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element maxOccurs="unbounded" name="p" type="xs:string" />
                              </xs:sequence>
                              <xs:attribute name="Sid" type="xs:string" use="required" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="summary" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="ISBN" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== maiyasser21/XML/Day2/Lab2/lab2.xml
<?xml version="1.0" encoding="UTF-8"?>

<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="schema.xsd">
    <info>
        <location>this is the location</location>
        <description>this is the desc</description>
        <librarian>this is the librarian</librarian>

    </info>
    <book ISBN="A_123">
        <title>this is the title</title>
        <author Name="AuthorName"></author>
        <preface>This is the Preface</preface>
        <part id="PartOneBookOne">
            <title>Part Title</title>
            <chapter>
                <title>Chapter Title</title>
                <section Sid="SectionOneB1C1">
                    <p>Paragraph One</p>
                    <p>Paragraph Two</p>
                    <p>Paragraph Three</p>
                </section>
                <summary>This is the chapter Summary</summary>
            </chapter>
            <chapter>
                <title>Chapter Title</title>
                <section Sid="SectionOneB1C2">
                    <p>Paragraph One</p>
                    <p>Paragraph Two</p>
                    <p>Paragraph Three</p>
                </section>
                <summary>This is the chapter Summary</summary>
            </chapter>
            <chapter>
                <title>Chapter Title</title>
                <section Sid="SectionOneB1C3">
                    <p>Paragraph One</p>
                    <p>Paragraph Two</p>
                   
                </section>
                <summary>This is the chapter Summary</summary>
            </chapter>
        </part>    
    </book>
    
</library>
